apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-6ihi
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-shhk-tenant/rhtap-demo-app/hacbs-test-project-6ihi@sha256:dbcf8c1cf585f393c2e27d000112d886d48824bbcad8b05ae2395fd885906a43
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
